/**
 * This class is generated by jOOQ
 */
package com.example.searchtoilet.jooq;


import com.example.searchtoilet.jooq.tables.Toilet;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.toilet
	 */
	public static final Toilet TOILET = Toilet.TOILET;
}
